backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
            - { label: 'Title', name: 'title', widget: 'string' }
            - { label: 'Description', name: 'description', widget: 'string' }
      - label: "About Page"
        name: "about"
        file: "content/_index.md"
        fields:
            - { label: 'Description', name: 'desc', widget: 'string' }
            - label: "Featured Image"
              name: "bg"
              widget: "image"
              default: "/uploads/chocolate-dogecoin.jpg"
              media_library:
                config:
                  multiple: false

